import { initMasks } from '../../core/js/masks.js';
import { initTabs } from '../../core/components/tabs.js';
initMasks(); initTabs();
const token = localStorage.getItem('token'); if (!token) location.href='../auth/login.html';
const api = async (u,m='GET',b=null)=>{const r=await fetch(u,{method:m,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:b?JSON.stringify(b):null});const j=await r.json();return{r,j}};
const list = document.getElementById('list'); const pager=document.getElementById('pager'); let page=1;
async function load(){const s=document.getElementById('search').value;const st=document.getElementById('status').value;const {j}=await api(`/api/v1/patients?search=${encodeURIComponent(s)}&status=${encodeURIComponent(st)}&page=${page}&per_page=10`);list.innerHTML='';(j.data.items||[]).forEach(p=>{const c=document.createElement('article');c.className='card';c.innerHTML=`<h3>${p.full_name}</h3><p>${p.email||'-'} · ${p.cpf||'-'}</p><div class='row-wrap'><button class='btn btn-sm' data-edit='${p.uuid}'>Editar</button><button class='btn btn-sm' data-del='${p.uuid}'>Excluir</button></div>`;list.appendChild(c);});pager.innerHTML=`<button class='btn btn-sm' id='prev'>Anterior</button><span>Página ${j.data.pagination.page}</span><button class='btn btn-sm' id='next'>Próxima</button>`;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>removeP(b.dataset.del));document.getElementById('prev').onclick=()=>{page=Math.max(1,page-1);load()};document.getElementById('next').onclick=()=>{page++;load()};}
async function edit(uuid){const {j}=await api('/api/v1/patients/'+uuid);const f=document.getElementById('patient-form');Object.entries(j.data).forEach(([k,v])=>{const el=f.querySelector(`[name='${k}']`);if(el)el.value=v??''});const {j:resp}=await api(`/api/v1/patients/${uuid}/responsibles`);document.getElementById('responsibles').innerHTML=(resp.data||[]).map(r=>`<article class='card'><strong>${r.name}</strong><p>${r.kinship||''}</p></article>`).join('');}
async function removeP(uuid){await api('/api/v1/patients/'+uuid,'DELETE');load();}
document.getElementById('btn-search').onclick=()=>{page=1;load()};
document.getElementById('btn-new').onclick=()=>{document.getElementById('patient-form').reset();};
document.getElementById('btn-save').onclick=async()=>{const f=document.getElementById('patient-form');const d=Object.fromEntries(new FormData(f));const isEdit=!!d.uuid;const {r,j}=await api(isEdit?`/api/v1/patients/${d.uuid}`:'/api/v1/patients',isEdit?'PUT':'POST',d);document.getElementById('feedback').innerHTML=`<div class='alert ${r.ok?'alert-success':'alert-error'}'>${j.message}</div>`;if(r.ok){f.querySelector('[name="uuid"]').value=j.data.uuid;load();}};
load();
