import { guardAuth, guardGuest, guardPermission } from './guards.js';

export const routes = [
  {
    path: '/login',
    layout: 'public',
    guard: guardGuest,
    module: () => import('../modules-loader.js').then(m => m.loadModule('auth/login')),
    title: 'Entrar',
  },
  {
    path: '/dashboard',
    layout: 'app',
    guard: guardAuth,
    module: () => import('../modules-loader.js').then(m => m.loadModule('dashboard/dashboard')),
    title: 'Dashboard',
    breadcrumb: ['Início'],
  },
  {
    path: '/company',
    layout: 'app',
    guard: guardPermission('company.view'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('company/company')),
    title: 'Empresa',
    breadcrumb: ['Início', 'Empresa'],
  },
  {
    path: '/schedule',
    layout: 'app',
    guard: guardPermission('schedule.view'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('schedule/schedule-page')),
    title: 'Agenda',
    breadcrumb: ['Início', 'Agenda'],
  },
  {
    path: '/schedule/appointment-types',
    layout: 'app',
    guard: guardPermission('schedule.event_types.view'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('schedule/appointment-types')),
    title: 'Tipos de Compromisso',
    breadcrumb: ['Início', 'Agenda', 'Tipos de Compromisso'],
  },
  {
    path: '/attendances/:uuid',
    layout: 'app',
    guard: guardPermission('attendance.view'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('attendances/attendance-detail')),
    title: 'Atendimento',
    breadcrumb: ['Início', 'Atendimento'],
  },
  {
    path: '/patients',
    layout: 'app',
    guard: guardPermission('patients.view'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('patients/patients-list')),
    title: 'Pacientes',
    breadcrumb: ['Início', 'Pacientes'],
  },
  {
    path: '/patients/new',
    layout: 'app',
    guard: guardPermission('patients.create'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('patients/patient-form')),
    title: 'Novo Paciente',
    breadcrumb: ['Início', 'Pacientes', 'Novo'],
  },
  {
    path: '/patients/:uuid/edit',
    layout: 'app',
    guard: guardPermission('patients.update'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('patients/patient-form')),
    title: 'Editar Paciente',
    breadcrumb: ['Início', 'Pacientes', 'Editar'],
  },
  {
    path: '/patients/:uuid',
    layout: 'app',
    guard: guardPermission('patients.view'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('patients/patient-detail')),
    title: 'Detalhe do Paciente',
    breadcrumb: ['Início', 'Pacientes', 'Detalhe'],
  },
  {
    path: '/specialties',
    layout: 'app',
    guard: guardPermission('professionals.view'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('specialties/specialties')),
    title: 'Especialidades',
    breadcrumb: ['Início', 'Profissionais', 'Especialidades'],
  },
  {
    path: '/professionals',
    layout: 'app',
    guard: guardPermission('professionals.view'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('professionals/professionals-list')),
    title: 'Profissionais',
    breadcrumb: ['Início', 'Profissionais'],
  },
  {
    path: '/professionals/new',
    layout: 'app',
    guard: guardPermission('professionals.create'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('professionals/professional-form')),
    title: 'Novo Profissional',
    breadcrumb: ['Início', 'Profissionais', 'Novo'],
  },
  {
    path: '/professionals/:uuid',
    layout: 'app',
    guard: guardPermission('professionals.view'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('professionals/professional-form')),
    title: 'Editar Profissional',
    breadcrumb: ['Início', 'Profissionais', 'Editar'],
  },
  {
    path: '/payment-tables',
    layout: 'app',
    guard: guardPermission('professional_payment.view'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('payment/payment-tables')),
    title: 'Tabelas de Pagamento',
    breadcrumb: ['Início', 'Financeiro', 'Tabelas de Pagamento'],
  },
  {
    path: '/payment-tables/new',
    layout: 'app',
    guard: guardPermission('professional_payment.create'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('payment/payment-table-form')),
    title: 'Nova Tabela',
    breadcrumb: ['Início', 'Financeiro', 'Nova Tabela'],
  },
  {
    path: '/payment-tables/:uuid',
    layout: 'app',
    guard: guardPermission('professional_payment.view'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('payment/payment-table-form')),
    title: 'Editar Tabela',
    breadcrumb: ['Início', 'Financeiro', 'Editar Tabela'],
  },
  {
    path: '/professional-payment',
    layout: 'app',
    guard: guardPermission('professional_payment.view'),
    module: () => import('../modules-loader.js').then(m => m.loadModule('payment/professional-payment-config')),
    title: 'Repasse Profissional',
    breadcrumb: ['Início', 'Financeiro', 'Repasse'],
  },
  {
    path: '/design-system',
    layout: 'app',
    guard: guardAuth,
    module: () => import('../modules-loader.js').then(m => m.loadModule('design-system/design-system')),
    title: 'Design System',
    breadcrumb: ['Início', 'Design System'],
  },
  {
    path: '/403',
    layout: 'app',
    guard: guardAuth,
    module: () => import('../modules-loader.js').then(m => m.loadModule('errors/error-403')),
    title: 'Acesso negado',
  },
  {
    path: '/404',
    layout: 'public',
    module: () => import('../modules-loader.js').then(m => m.loadModule('errors/error-404')),
    title: 'Página não encontrada',
  },
];
